###########
# site.title

title:    'Project IfYouCanDodgeAFireball'
subtitle: 'CS 175 Project in AI'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
